### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by soaj1664** [Viralmaniar/Passhunt#4]
Getting

`python passhunt.py
Traceback (most recent call last):
  File "passhunt.py", line 11, in <module>
    import urllib.request
ImportError: No module named request`

Would you please check? Thanks!

**Comment by BaderSZ** [comment]
Hey,

I had his issue as well. How are you calling/starting the script?

This usually happens if you use an unsupported version of python being called or the module isn't installed for said python version. The script calls /usr/bin/python by default, but Debian stable links that with python2.7 while the script requires 3.5 and above.

I'll send a pull request later to repair that by calling /usr/bin/env, which i'd argue is much cleaner. Just call the script with python3 or whatever's applicable in your OS/Distro, and it should work.
